### ISSUE TITLE
[QUESTION] Did a plugin update break rescheduling for anyone who doesn't update the JavaScript scheduler portion?

### ISSUE THREAD

**Issue by kylegoetz** [open-spaced-repetition/fsrs4anki#177]
I have Anki auto-update plugins. I installed this plugin back in January and did the optimizer to get the `w` value. Rescheduled to apply FSRS-based scheduling.

Then I spent two months flashcarding. I was under the impression that the rescheduling would be applied automatically.

But yesterday out of curiosity (wondering why I was getting only 70% retention on mature cards instead of the targeted 90%) I tried to apply rescheduling and got a cryptic error message (I opened a ticket for this).

Based on latest advice in my ticket, I updated the Scheduler. Now it works, but my due date for today jumped from 200 to 1000 cards.

Why did this happen? Shouldn't the card due date (theoretically) have not changed *at all* since the scheduler should have been running this whole time?

Or is one meant to manually click "re-schedule" every time you flashcard, and it's not done automatically?

I only use this on my Mac. No Android, no iPhone, nothing.

**Comment by kylegoetz** [comment]
This happened to me when I first installed the plugin, went from a couple hundred due to a few hundred. This jump is even bigger, but the scheduler should've been running all the time, right? Why did it find 700–800 cards that should be moved earlier?

**Comment by L-M-Sherlock** [comment]
The rescheduling isn't applied automatically. And the interval scheduled by the Helper is different from the FSRS4Anki Scheduler in some cases. Because the Helper will reschedule cards based on their entire review history, which is different from the FSRS4Anki Scheduler. The Helper will also reschedule those cards scheduled by the FSRS4Anki Scheduler. It is a feature, not a bug. It could reschedule the card with the new parameters of FSRS4Anki if you used the optimizer to generate personalized parameters for yourself. The interval given by the Helper is more accurate than the Scheduler. Besides, the fuzz feature is implemented differently between the Helper and Scheduler because the random function in Python and Javascript is inconsistent.

**Comment by kylegoetz** [comment]
Couple follow up questions then:

1. the plugin does nothing unless I manually tell it to reschedule (say, at the end of every review session)?
2. What is the purpose of the JavaScript if the plugin does the rescheduling, and only does it with a manual menu click?

Thansk!

**Comment by kylegoetz** [comment]
(Also is this documented anywhere that the plugin does not do rescheduling on its own? This seems like a really important thing to have. Maybe I missed it when I followed the instructions for setting it up. I don't recall the instructions saying that you needed to keep doing this.)

**Comment by MNastri** [comment]
> 1. the plugin does nothing unless I manually tell it to reschedule (say, at the end of every review session)?

Yes. To reschedule cards, set your parameters and then click on 'Tools' and select 'Reschedule cards'. [[source](https://github.com/open-spaced-repetition/fsrs4anki/wiki/Usage#helper)]

> 2. What is the purpose of the JavaScript if the plugin does the rescheduling, and only does it with a manual menu click?

The JS code automatically schedules cards as you review them, so you can use it exclusively if you prefer. Additionally, this is the same code that the helper reads to fetch your configuration when you run it. [[source](https://github.com/open-spaced-repetition/fsrs4anki/wiki/Usage#scheduler)]
 
> All this talk of helper, scheduler, etc. is confusing me. There's a plugin, there's JS we're supposed to paste into the options of the app, there's the ipyb stuff that runs the simulations to generate the `w` that goes in the JS, and then there's a separate script you're supposed to use to keep Android and Anki decks scheduled the same.

Let me help clear up that confusion for you.
scheduler  --> The scheduler uses the FSRS model to schedule cards when reviewing. [[source](https://github.com/open-spaced-repetition/fsrs4anki/wiki/Usage#scheduler)]
helper -----> The helper can assist with more accurate rescheduling of cards, but only if you wish to use it. It's especially helpful for rescheduling cards reviewed before using the custom scheduler or that were reviewed on Android since it doesn't support custom schedulers. [[source](https://github.com/open-spaced-repetition/fsrs4anki/wiki/Usage#helper)]
ipyb stuff --> These are the optimizer and the simulator. The optimizer and simulator are two separate tools. The optimizer reads your revision history and provides optimized weights [[source](https://github.com/open-spaced-repetition/fsrs4anki/wiki/Usage#optimizer)], while the simulator predicts how future revisions will go using a given set of weights. [[source](https://github.com/open-spaced-repetition/fsrs4anki/wiki/Usage#simulator)]

> (Also is this documented anywhere that the plugin does not do rescheduling on its own? This seems like a really important thing to have. Maybe I missed it when I followed the instructions for setting it up. I don't recall the instructions saying that you needed to keep doing this.)

The helper doesn't schedule anything on its own because that's the scheduler's job. It simply provides help with rescheduling the cards. 
However it does guide users to set their parameters and then click `Tools -> Reschedule cards` in order to use it so there shouldn't be any confusion about how it works.

I hope this helps and make sure to read the [usage page](https://github.com/open-spaced-repetition/fsrs4anki/wiki/Usage)

**Comment by kylegoetz** [comment]
OK, then I'm really confused. (And FWIW the bolded text is to highlight my main question, not to signal that I'm yelling)

I used the optimizer to generate `w`.

Then I installed the plugin (which is the scheduler) and also copy pasted the JS with the optimizer's custom `w` value pasted into it. From reading the instructions, I did an initial rescheduling. So I understand that part of what you wrote.

>The JS code automatically schedules cards as you review them, so you can use it exclusively if you prefer.

Here's where the confusion comes in. I have had the JS code (which is also the scheduler?) since then. When I created this ticket a few days ago, I had on a whim done the plugin's "tools -> reschedule cards." It made 700+ additional cards due that day.

So if the JS should have been scheduling automatically, **why did the plugin reschedule all these 700+ cards to be due today** even though

1. I'd used it to reschedule existing cards right after calculating the `w` thing
2. I've had the JS pasted with the calculated `w` value since that day

**Comment by MNastri** [comment]
I believe I failed to remove the confusion. 

Scheduler = The code written in JavaScript that goes into the custom scheduler field in Anki.

Helper = addon for Anki that reads the custom scheduler field when it is run.

The reason you had 700 other reviews I believe was clarified on the other issue (you had duplicated the weights and the scheduler used the incorrect one for two months IIRC)

**Comment by kylegoetz** [comment]
＠MNastri what do you mean I had duplicated the weights? I only ever had the `w` in one place, and that's the JavaScript. I copy and pasted the JS code back in Jan from this repository, replaced the existing `w` with mine, and that's it. I checked the Anki plugin config, and its entire contents are

```json
{
    "days_to_reschedule": 7,
    "free_days": [],
    "load_balance": false
}
```

The JS was the scheduler as it was in January with the global `w` replaced with mine. There were no deck-specific configs.

**Comment by L-M-Sherlock** [comment]
> I'm trying to figure out what exactly I desperately need to fix to get this thing working right!

I guess it is the same issue to https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/33

**Comment by MNastri** [comment]
> I'm trying to figure out what exactly I desperately need to fix to get this thing working right!

Remove the commented out line and rerun the helper (ctrl+r)
