### ISSUE TITLE
[BUG] Got "0 seconds" interval after reviewing with "Good" rate

### ISSUE THREAD

**Issue by YorkZ** [open-spaced-repetition/fsrs4anki#18]
**Describe the bug**
Got scheduled at "0 seconds" interval after reviewing with "Good" rate

**To Reproduce**
1. Click the filtered deck with the filter
```
   deck:XXXX is:due is:learn
```
2. Click on `Study Now`
3. Click on `Show Anwer`
4. Click on `Good` button

**Expected behavior**
Scheduled with a non-zero interval

**Screenshots**
See the attached screenshot

**Environment**
 - Anki version: dev version 2.1.55
 - OS: Arch Linux
 - Scheduler version: V3
 - Optimizer version: git commit eccd894 
 - Simulator version: N/A

![2022-09-22_23-26](https://user-images.githubusercontent.com/742238/191869587-5d8c1467-4c21-427c-9d91-f920304938fd.png)

**Comment by L-M-Sherlock** [comment]
I need the Scheduler version of FSRS4Anki that you used.

**Comment by L-M-Sherlock** [comment]
Test this branch's scheduler.js.

**Comment by YorkZ** [comment]
> I need the Scheduler version of FSRS4Anki that you used.

It's commit eccd894.

**Comment by L-M-Sherlock** [comment]
Can you test this? https://github.com/open-spaced-repetition/fsrs4anki/blob/fix/interval%3D0/fsrs4anki_scheduler.js

**Comment by YorkZ** [comment]
Is it OK to use 7440ccf?

**Comment by L-M-Sherlock** [comment]
Yes.

**Comment by L-M-Sherlock** [comment]
I found that what my fix solved is another bug……

**Comment by khonkhortisan** [comment]
[solved][posterity] I assume this screenshot is caused by the same issue, and also already fixed. I was using the scheduler before 1.0.0 (before it had constrain_value) with auto ease factor and bury siblings and multiple addons throwing various errors, and am now on 1.4.2. good and easy say (end) as if it was a filtered deck that doesn't affect scheduling, customData.s is null, answer confirmation says it's scheduled for 0 days, the card was coming back after I left and re-entered the review session. I rescheduled the repeating cards as new
![imagen](https://user-images.githubusercontent.com/1996449/192151706-804b447d-fcf2-470a-a7ca-b3565cb115dd.png)

**Comment by L-M-Sherlock** [comment]
> as if it was a filtered deck that doesn't affect scheduling

In this case, the state of scheduling is `preview`, so the algorithm will skip all the calculation.
