### ISSUE TITLE
Why should the graduating interval/learning steps be kept low with FSRS?

### ISSUE THREAD

**Issue by salmanuc** [open-spaced-repetition/fsrs4anki#346]
**Research**

*Enter an [x] character to confirm the points below:*

- [x ] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [ x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [ x] I have searched for similar existing questions here (extensively like 3-4 hours)

**Question**

Why should the graduating interval/learning steps be kept low with FSRS?
What is considered as long interval by fsrs  (from faq it seems maybe 1 day)?

I am a medical student who uses anki first to learn the content in cards which means pressing again a few times. I therefore use graduating interval as 11 days with learning steps as 2h 1d 4d 10d so that i don't have ease hell mode on. After the learning phase is over, its mostly good.

Feature request: can you add the option in fsrs to ignore any data for the card before x number of days has been achieved as an interval and to use data after that step for rescheduling purpose? 

Thank you.

**Comment by L-M-Sherlock** [comment]
Please see this issue: https://github.com/open-spaced-repetition/fsrs4anki/issues/343

**Comment by user1823** [comment]
@salmanuc, the answer to your question is as follows:

Due to technical limitations, the FSRS scheduler doesn't know about the reviews that occur in the learning steps. So, even if the last learning step is greater than 1 day, the first interval set by the FSRS scheduler can be smaller than 1 day. To prevent this unexpected behaviour, it is recommend to not use learning or relearning steps of more than or equal to 1 day.

If you still want to use learning (or relearning) steps greater than one day, it is recommended to reschedule your cards daily using the FSRS helper add-on. The helper add-on can read the entire review history of the card and, thus, provide more accurate next intervals in such cases.

@L-M-Sherlock, I would request you to add the above to the FAQs. It would end a lot of confusion that exists among the users relating to the learning steps.

**Comment by salmanuc** [comment]
@L-M-Sherlock can you perhas add the feature requested or should i create a new thread for feature request?

**Comment by L-M-Sherlock** [comment]
> can you perhas add the feature requested or should i create a new thread for feature request? This would make med students life easier who use anki to retain as well as learn material.

I don't support to drop out any long-term reviews.

**Comment by user1823** [comment]
@L-M-Sherlock, this is to remind you to add https://github.com/open-spaced-repetition/fsrs4anki/issues/346#issuecomment-1632322282 to the FAQs.

**Comment by L-M-Sherlock** [comment]
Added.
