### ISSUE TITLE
[BUG] Inconsistency between Colab notebook version and Hugging face app version

### ISSUE THREAD

**Issue by JeffersonCorreia32a** [open-spaced-repetition/fsrs4anki#402]
**Research**

*Enter an [x] character to confirm the points below:*

- [x ] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x ] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x ] I have searched for similar existing questions here

**Question**
Dear all,

I kindly request to understand why the two optimizers are giving different results. Are they not on the same version parity?

Below is the result of the optimizer in Colab version 4.4.5:
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/138017463/a1a6bb68-7b36-4b09-bbe1-be9c082a47c6)

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/138017463/0449e436-f341-4730-bda0-188cea665001)

Below is the result of the optimizer in the app: 
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/138017463/15ace994-b74c-4853-9f5d-10a3bc50d3d6)

Shouldn't they be giving the same result?

**Comment by galantra** [comment]
You write that colab is v4.4.5, whereas the app is 4.5.5.

**Comment by L-M-Sherlock** [comment]
Weird. I also get a different result. But the codes and versions are the same. It could be caused by the environment.

**Comment by L-M-Sherlock** [comment]
I spend 3 hours in this inconsistency, but didn't find out the problem. Maybe someone could help me solve it.

**Comment by JeffersonCorreia32a** [comment]
> Passei 3 horas nessa inconsistência, mas não descobri o problema. Talvez alguém possa me ajudar a resolver.


Thank you for your attention, and let's wait to understand what caused this difference. But in the case of this difference, which is the most recommended to use at the moment? the collab or the hugging?

**Comment by L-M-Sherlock** [comment]
The difference is nuanced, so they both are OK.

**Comment by brubsby** [comment]
It seems possible that the miniscule differences are probably due to the ML algorithms running on different hardware and having low level calculations be done slightly differently. For one of my decks I get these weights on 4.14.2 hugging face vs colab:
[3.4197, 7.4713, 13.6191, 29.5346, 4.6397, 1.0871, 1.2327, 0.0021, 1.9945, 0.1, 1.4182, 2.0051, 0.1376, 0.2627, 1.2266, 0.0878, 3.4772]
[3.3774, 7.5505, 13.7338, 29.5574, 4.6232, 1.0913, 1.2979, 0.0036, 1.9905, 0.1, 1.4236, 2.0429, 0.1618, 0.2581, 1.2049, 0.0789, 3.5195]

[It seems](https://huggingface.co/blog/huggingface-and-amd) hugging face has partnered with AMD, and is using AMD CPUs in the default instance, and google colab uses [intel processors](https://saturncloud.io/blog/whats-the-hardware-spec-for-google-colaboratory/#:~:text=The%20default%20CPU%20for%20Colab,vCPUs%20and%20624GB%20of%20RAM.). I think this alone might explain it, the difference could be as simple as python using different rng algorithms per architecture (or the default instance having slightly different python installation or something), or something like floating point math intricacies in each architecture or compiler. If it resulted in huge differences in loss after training, it might be worth pursuing, but seems benign now.

for my deck from above:
hf loss: 0.1282
gc loss: 0.1271

and I imagine different decks would look much the same, as well as using a different rng seed within one environment.
