### ISSUE TITLE
[Question] What is the meaning of the configuration params? Is there a formula I can use to calcua

### ISSUE THREAD

**Issue by bensmiley** [open-spaced-repetition/fsrs4anki#420]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

I am building an app so I would like to offer a custom UI to allow the user to make their own parameters. Is there a formula to do this? 

Like: 

w(1) = 
w(2) = 
etc...

I'm sorry if this exists already, I did check but I couldn't find it.

**Comment by L-M-Sherlock** [comment]
Here only are the formula: https://github.com/open-spaced-repetition/fsrs4anki/wiki/The-Algorithm

It is hard for me to name the parameters.

**Comment by bensmiley** [comment]
What I mean is that I saw this: 

![Screenshot 2023-08-11 at 12 11 47](https://github.com/open-spaced-repetition/fsrs4anki/assets/5514010/321d2084-2266-407b-a1e0-68eb2883677d)

Is there an example of the code that can convert these human readable parameters into the internal parameters?

**Comment by L-M-Sherlock** [comment]
> Is there an example of the code that can convert these human readable parameters into the internal parameters?

What do you mean the human readable parameters?

**Comment by bensmiley** [comment]
What I'm trying to work out is how would the parameters be modified? If a user wanted to change them, how would they go about doing that?

In the above example, there are understandable properties like "easy bonus" or "hard interval". Is there a way that these kind of human-understandable properties can be translated into a configuration parameters that seem more abstract and hard to define?

**Comment by L-M-Sherlock** [comment]
> What I'm trying to work out is how would the parameters be modified? If a user wanted to change them, how would they go about doing that?

Just use FSRS optimizer to do that automatically. Here is the repo: https://github.com/open-spaced-repetition/fsrs-optimizer

**Comment by L-M-Sherlock** [comment]
I don't recommend modifying the parameters manually, except the professional users.

**Comment by Expertium** [comment]
> In the above example, there are understandable properties like "easy bonus" or "hard interval". Is there a way that these kind of human-understandable properties can be translated into a configuration parameters that seem more abstract and hard to define?

@bensmiley This may sound rude, but if you want to make an app where users can manually change those parameters, then you are missing the whole point of FSRS. The point is to:
1) Stop relying on human judgement and use math instead
2) Make it so that the users only have to choose 1-2 parameters and forget about tweaking
With FSRS, users don't have to worry about things like "Hmmm, should I increase or decrease this value?". And the optimizer can find the optimal values far more accurately than any user ever will be able to. So I really, _**REALLY DON'T**_ recommend using the FSRS algorithm to make an app, but then letting the users choose the parameters. This will create even more confusion (and people are already confused about a lot of Anki settings) and will nullify advantages of FSRS. Instead, I recommend you to make an app with as few "visible" parameters in the UI as humanly possible, and leave the rest to the computer.
