### ISSUE TITLE
[Feature Request] Please add an option

### ISSUE THREAD

**Issue by Golddouble** [open-spaced-repetition/fsrs4anki#460]
**Which module is related to your feature request?**
Scheduler

**Is your feature request related to a problem? Please describe.**
Until now I only have used sm-18 algo. But I guess FSRS is very similar to sm-18. 
My experience with sm-18 is the following: I have a lot of Items that I only can rate with "3". 
But next time I again can rate it only with "3". And so on.
After only a few repetitions, SM gives makes an interval of 2 years for this item. Then these 2 years are over and I have to rate this item with "1". 

When I look at my collection, I have far too many items that I rated "3" in the last repetition. (Maybe 60%). I know, I could reduce the forgetting index, but I don't want to. I want the algo to react more specifically to items with a rating of "3".

**Describe the solution you'd like**
I assume that FSRS behaves similarly to the sm-18 algo in this respect. 
Here is my suggestion for FSRS: 
I would welcome an option in the scheduler (or in a better fitting plugin), that could be activated or inactivated and makes the following:

Rule of this option: 
1. Test, if the interval of this Item was <= 100 days, bevor the current review
2. For Items, that fulfill point 1), check if they were rated with "3" after the current review
3. For Items, that fulfill point 2), make a max. Interval of 100 days. (If the optimal Interval would be 300 days, it should reduce it to 100 days)

(This will happen until I will rate this Item with "4" or better.)

This would prevent items, that are not yet well anchored in the memory, from quickly getting high intervals. At the same time, it would prevent an unnecessarily high number of repetitions in the range of interval lengths 1-99.

**Comment by Expertium** [comment]
FSRS isn't exactly the same as SM-18, plus SuperMemo has 6 grades, whereas Anki has 4.
I would suggest you try FSRS for a few months and see how intervals grow. Right now, it seems to me that you have used FSRS for a very short period of time and just assumed how it may work instead of observing it.
If you feel like you want to see cards more often, then you can increase your requested retention. If you are not satisfied with the results after that, then feel free to come back to this issue.
