### ISSUE TITLE
[Question] AUTO RESCHDEULE and AUTO DISPERSE SIBLINGS slow down the responsiveness during review

### ISSUE THREAD

**Issue by fredjoe7** [open-spaced-repetition/fsrs4anki#480]
**Research**

*Enter an [x] character to confirm the points below:*

- [x ] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x ] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x ] I have searched for similar existing questions here

**Question**

turning "on" RESCHDEULE CARDS WITH EACH REVIEW and AUTO DISPERSE SIBLINGS seems to slow down the responsiveness during review. It makes it look like the PC is slow. Disabling those two options seems to bring back the responsiveness during review.

Hoping this could be resolved.

**Comment by L-M-Sherlock** [comment]
It's hard to improve the performance in the add-on, because it is implemented in Python.

**Comment by fredjoe7** [comment]
will the responsiveness improve after integrating with anki ?

**Comment by L-M-Sherlock** [comment]
After the integrating, you don't need AUTO RESCHDEULE. But AUTO DISPERSE SIBLINGS hasn't been integrated into Anki.

**Comment by fredjoe7** [comment]
ok thankyou

**Comment by filipenanclarez** [comment]
> After the integrating, you don't need AUTO RESCHDEULE. But AUTO DISPERSE SIBLINGS hasn't been integrated into Anki.

Do you have plans to implement it integrated with Anki? Is there an open issue for this? Until then, what's the best advice for decks with lots of siblings, and reviews mostly done on mobile?

**Comment by L-M-Sherlock** [comment]
We plan to integrate load balance and easy days at first.
- https://github.com/ankitects/anki/issues/3116

**Comment by L-M-Sherlock** [comment]
> what's the best advice for decks with lots of siblings, and reviews mostly done on mobile?

I have improved the performance of add-on during this year. Do you still feel slow when AUTO RESCHDEULE and AUTO DISPERSE SIBLINGS?

**Comment by filipenanclarez** [comment]
> > what's the best advice for decks with lots of siblings, and reviews mostly done on mobile?
> 
> I have improved the performance of add-on during this year. Do you still feel slow when AUTO RESCHDEULE and AUTO DISPERSE SIBLINGS?

I'm not using the AUTO RESCHDEULE option because I already use FRSR integrated with Anki.

And the AUTO DISPERSE SIBLINGS *WHEN REVIEW* option scared me, because of the warning in the documentation. Plus, I do most of my reviewing on my phone, so I assume this option won't help me, right?

**Comment by L-M-Sherlock** [comment]
Yeah. But you can use `auto disperse siblings reviewed in other device after sync`.

**Comment by filipenanclarez** [comment]
> We plan to integrate load balance and easy days at first.
> 
> * [Integrations of Load balance & Easy days ankitects/anki#3116](https://github.com/ankitects/anki/issues/3116)

I know you may already have good reasons for choosing to do this first, but I would like to share my point of view as a user and student.

I understand that the "Disperse Siblings" feature is much more relevant, and should be resolved first, because it directly affects retention in sets that have many 'Siblings'. In my case, each note has 8 siblings. I notice interference between cards several times, in some cases, a serious interference, which sometimes makes me play a card for 1 year in advance, when I know it is a card that I would not remember, if I had not seen a sibling of it one minute before. Sometimes when I see the sibling, I mark it as forgotten, but when I see its pair, I mark it as good, because I actually remembered what it means, but I know that I remembered it because of its pair seen a few minutes ago.

Using the 'bury siblings' option doesn't help much, because it only moves forward one day, which sometimes makes me see the same note 8 days in a row, just in different ways.

Even though I have the add-on, in my case, I need to keep logging into the computer, to ensure that they are dispersed 'after sync', but if I'm traveling, for example, away from my computer for a few days, this can be an inconvenience .

Anyway, I'll use it this way until this is completed.

Thank you also for taking the time to respond.
