### ISSUE TITLE
[Question] Learning steps restart after relearning the card

### ISSUE THREAD

**Issue by artjomsR** [open-spaced-repetition/fsrs4anki#483]
**Research**

*Enter an [x] character to confirm the points below:*

- [X] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [X] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [X] I have searched for similar existing questions here

**Question**
I have noticed that when I have already learnt a card (e.g. with an interval with several days) press Again and go through the relearning steps, the interval restarts from the beginning and the steps are set as if the card is being learnt for the first time. This feels counter-intuitive to me as the card was already studied previously, so there's no need to have as short intervals compared to the card that is being studied for the first time.

I believe this is how SM does this as well - after failing, interval starts at a few days, but then grows much faster compared to fully new cards

I know that you've written previously about the limitation of Anki and V3 scheduler so I wonder if this is a limitation of these factors.

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/6875790/0e352f0e-f96d-4b7a-94b0-4d1c8c3a5023)
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/6875790/54389b8a-d702-4d5a-98bd-87b01a28501f)

**Comment by L-M-Sherlock** [comment]
FSRS doesn't control the schedule in (re)learning steps.

**Comment by artjomsR** [comment]
So to be clear, I'm not asking about the relearning steps themselves. I understand that I manually set them as `7m` in my Anki deck settings. What I'm asking about is the steps that the card gets after it exits the relearning stage. On my screenshot it is days 18, 19 and 22 of September

Basically, as you can see in the info highlighted by the red rectangles, the steps were 1-2-5-10, I forgot the card and the next steps are 1-3-5 again (the second step, `2` vs `3`, is different but I assume that's because of the fuzz). Are these steps deliberately similar or this a limitation of Anki?

**Comment by L-M-Sherlock** [comment]
> I believe this is how SM does this as well - after failing, interval starts at a few days, but then grows much faster compared to fully new cards

Could you provide this source?

By the way, I recommend reading this page for more details about the algorithm: https://github.com/open-spaced-repetition/fsrs4anki/wiki/The-Algorithm

**Comment by L-M-Sherlock** [comment]
By the way, I think it's bad to let a failed card's interval grow faster then fully new cards. A failed card usually is hard than new cards, so its interval should grow slower than new cards.

**Comment by Expertium** [comment]
@artjomsR you can use this to see what kind of intervals you get with your parameters, a specified review history and a specified level of desired retention.
https://huggingface.co/spaces/open-spaced-repetition/fsrs4anki_previewer
Example:
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/851e6dc2-d719-4b65-8629-0f83e2649451)
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/2b477785-e8be-4886-8909-355b11f3dac3)

Btw @L-M-Sherlock, I have a request - add a new interval/prev. interval ratio, so that it would be easy to see exactly how much the interval has increased after each review. Add this to both the hugging face version and to the google colab version. Idk if I should make a separate issue for it.
