### ISSUE TITLE
What is the relevant retention metric?

### ISSUE THREAD

**Issue by wadid** [open-spaced-repetition/fsrs4anki#499]
FSRS Stats say for a new one month old deck: Average retention: 95.14%, Average stability 27days. 
Then for True retention Day 69%, Yesterday 85%, Week: 77,8%, Month 71,4%

In the settings I did set "requestRetention": 0.85

What is the relevant metric to watch here? Average Retention (this seem to come from FSRS4Anki) or True Retention?

Because if the goal is retention of 0.85 then "True Retention" 71% to 85% seems low and "Average Retention" 95% seems high.

**Comment by L-M-Sherlock** [comment]
Average retention: the average probability of recalling a card today. In most cases, it is higher than requested retention because requested retention refers to retention at the time of a review, whereas average retention is calculated based on all cards, including undue cards. This is calculated using FSRS formulas and depends on your parameters.

**Comment by user1823** [comment]
True Retention is the relevant metric to be observed.

> if the goal is retention of 0.85 then "True Retention" 71% to 85% seems low

Did you optimize the parameters using your collection? If not, I advise you to do it.
If you have already optimized the parameters, I would recommend re-optimizing them every month for atleast a few months because your collection is new. Later, you can re-optimize every 3 months or so.

**Comment by wadid** [comment]
so @L-M-Sherlock says Average retention and @user1823 says True retention? I am confused.

I am not really experienced with these values. Sp does true retention between 71% (month) and 85% seem too low at all or is that normal range?

Good idea to optimize the parameters. I did it now with huggingface. But something I am wondering is that in the analysis tab it also said suggested retention rate 0.84. I dont understand why does hugging face also suggest a retention rate? What is the benefit of that?

**Comment by user1823** [comment]
> @L-M-Sherlock says Average retention and @user1823 says True retention? I am confused

L-M-Sherlock told you why Average Retention is expected to be higher than your request retention.

But, to know whether FSRS is fulfilling its promise or not, you need to check whether the True Retention is nearly the same as your request retention or not.

> I dont understand why does hugging face also suggest a retention rate? What is the benefit of that?

It tries to calculate a retention rate that maximizes the total knowledge. It's experimental and it's probably better to use your own intuition to come up with a request retention. However, the suggested retention can be used when the user has no idea of what they want their retention rate to be.

**Comment by Expertium** [comment]
@wadid the naming convention can be quite confusing. Average retention can be interpreted as the probability of recalling **any** card from your deck/collection today. True retention refers to the probability of recalling a card that is **due** today. Not every card is due. Most cards aren't due. So average retention is higher than true retention.

**Comment by Expertium** [comment]
It's hard to say how much granularity is good. You could create like 20 different decks, but I doubt that it would be beneficial.
If you don't mind doing a bit of number crunching, you can do this:
1) Click "Evaluate" (next to "Optimize"), write down RMSE
2) Split cards based on your subjective judgement and put some of them into a different deck, so that deck 1 has easy cards and dekc 2 has hard cards (or the other way around, doesn't matter)
3) Calculate new optimal parameters for both decks and click "Evaluate"
If RMSE(all cards in the same deck)>RMSE(cards in deck1) and RMSE(all cards in the same deck)>RMSE(cards in deck2), in other words, if RMSE if the deck with all cards is higher than RMSE of individual decks after splitting, that means splitting helped to reduce the prediction error. If RMSE is about the same for all 3 decks (full, deck1, deck2), then that means it doesn't matter.
But even I don't care that much, and I consider myself a "power user". I just group cards based solely on their content, for example, I use different parameters for geography, English and Japanese.

**Comment by wadid** [comment]
I guess I will keep it just all in one deck and optimize the parameters.

**easy and difficult mixed together in one deck:**
default parameters:
Log loss: 0.3546, RMSE(bins): 9.91%. Smaller numbers indicate a better fit to your review history.

optimized parameters:
Log loss: 0.3419, RMSE(bins): 6.47%. Smaller numbers indicate a better fit to your review history.

---
**easy card deck without difficult cards**
default parameters:
Log loss: 0.0985, RMSE(bins): 9.01%. Smaller numbers indicate a better fit to your review history.

optimized parameters:
Log loss: 0.0260, RMSE(bins): 1.29%. Smaller numbers indicate a better fit to your review history.

---
**difficult card deck without easy cards**
default parameters:
Log loss: 0.4787, RMSE(bins): 13.47%. Smaller numbers indicate a better fit to your review history.

optimized parameters:
Log loss: 0.4363, RMSE(bins): 7.95%. Smaller numbers indicate a better fit to your review history.
