### ISSUE TITLE
[Question] What is the best practice for reschedule cards and update parameters button?

### ISSUE THREAD

**Issue by ratman-codes** [open-spaced-repetition/fsrs4anki#605]
I would like to understand what the recommended cadence to hit reschedule all cards is. Is this meant to be hit daily or another best practice? I currently am rescheduling daily, and updating my FSRS parameters about weekly but not really being strict about it.

**Comment by L-M-Sherlock** [comment]
Update the parameters once a month is enough. For long-term study, there is no need to reschedule all cards. Only reschedule all cards when you want to achieve your desired retention as soon as possible.

**Comment by user1823** [comment]
- "Reschedule all cards" should be used only after updating the parameters or desired retention. However, you can use "reschedule cards reviewed in last x days" daily if you want to use load balancing. In this case, I recommend setting a low value of x (such as 1, 2 or 3) in the add-on config so that you don't unnecessarily reschedule cards multiple times.
- You should update the parameters only after you have done at least 4000 reviews since the last optimization. For example, if you do 100 cards each day, re-optimize not earlier than 40 days after the last optimization. Otherwise, chances are high that you will get worse parameters after optimization.

For future questions, please use Anki Forums (https://forums.ankiweb.net/).

**Comment by ratman-codes** [comment]
Thanks for the prompt answer. I'd like to ask one follow-up, why does it matter that you've done 4k reviews since last optimization? Doesn't it look at the entire histroy of reviews?

**Comment by brishtibheja** [comment]
@user1823 I accidently and part curiously did optimize the parameters twice in one day (when I started using fsrs). what should I do now or if there is anything I can do to mitigate some of the harm I've done?

**Comment by aleksejrs** [comment]
@brishtibheja The changes of the new parameters being worse are not because you optimized after a short time, but because the result is kind of fuzzy.
